Feature karidata rama
Laboratoria/CDMX009-Data-Lovers pull request #13
Opened 2020-03-10 17:21 UTC by Kari2406

2020-03-10 17:33 UTC, YeraldinCasas approved these changes

2020-03-25 05:39 UTC, HectorBlisS requested changes
Los  comentarios en los commits pueden mejorar mucho, sean más semanticas y descriptivas, eviten los "ahora si"  y haganlo todo en  ingles, felicidades por el  app,   muy interezante.

2020-03-25 05:39 UTC, HectorBlisS commented on src/main.js
> +});
Si lo que colocas dentro del cuerpo de la función es 1 sola linea, este puede ir directo como "expresion":
```

let newCleanData = cleanData.map(cleanData=>cleanData.name);
```
Si lleva llaves se llama "bloque", si solo es una linea frente al arrow function se llama "expresión"

2020-03-25 05:39 UTC, HectorBlisS commented on src/main.js
> +    return el.toLowerCase().indexOf(typeName.toLowerCase()) > -1;
Otra expresión aquí

2020-03-25 05:39 UTC, HectorBlisS commented on src/style.css
>    box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
super!

2020-03-25 05:39 UTC, HectorBlisS commented on src/index.html
> +                      <input type="button" class="searchBtn" id="search" value="Buscar" onclick="filterDataName()">
Todo bien aquí, pero regularmente las clases css no van con camelCase (search-box)

2020-03-25 05:39 UTC, HectorBlisS commented on src/main.js
> +  for (let i = 0; i < heading.length; i++){
Un forEach o un map, te ayudan con la semántica y la identación, esto podría quedar más simple.

2020-03-25 05:39 UTC, HectorBlisS commented on src/main.js
>      th.appendChild(document.createTextNode(heading[i]));
bien

2020-03-25 05:39 UTC, HectorBlisS commented on src/data.js
>        name: item.resource.name[0].given[0]+" "+item.resource.name[0].family[0],
Hermoso

2020-03-25 05:39 UTC, HectorBlisS commented on src/main.js
> +  table.appendChild(tableBody);
Muy bien la creación de la tabla, pero con `` puede crearse de forma más simple.

2020-04-03 18:11 UTC, closed without merging